backend:
  name: github
  repo: catalinacs/tum-web-lab2
  branch: main
  auth_endpoint: https://decap-auth.samecatalina.workers.dev/auth
local_backend: false
site_url: https://tum-web-lab2.pages.dev

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    format: frontmatter
    files:
      - label: "Landing Page"
        name: "landing"
        file: "index.njk"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Description", name: "hero_description", widget: "text" }
          - { label: "About Title", name: "about_title", widget: "string" }
          - { label: "About Description", name: "about_description", widget: "text" }
          - { label: "Services Description", name: "services_description", widget: "text" }
          - label: "Cookies"
            name: "cookies"
            widget: "list"
            fields:
              - { label: "Cookie Name", name: "cookie_name", widget: "string" }
              - { label: "Cookie Description", name: "cookie_description", widget: "text" }